Made maxLines property nullable and added assertions
danvick/flutter_form_builder pull request #810
Opened 2021-05-20 12:33 UTC by S-ecki

made `maxLines` property nullable
added assertions for proper use of `expands`

resolves #809

2021-05-20 16:06 UTC, danvick commented
Hi @S-ecki,

Kindly note that your changes have brought about CI build failure. Please resolve the issues before we can merge this PR

2021-05-20 16:11 UTC, danvick requested changes
Line 303 is still setting a default value for `maxLines`. 

If `maxLines` is to be nullable, then we'd need to remove the default value for the property. Otherwise, it won't be nullable.

2021-05-20 23:50 UTC, S-ecki commented
I believe the problem was a false assertion that I inserted.
Setting a `maxLines` default value should be compatible with it being nullable as Flutter´s `TextFormField` has implemented it the same way. 

However, I could be mistaken and await your review!

2021-06-06 07:32 UTC, tahesse commented
Hey, what's the status of this PR? 😅

2021-06-06 10:20 UTC, S-ecki commented
> Hey, what's the status of this PR? 😅

I commited changes that (as far as I can tell) solve the issue and do pass the tests, so I am waiting on a response.

Perhaps you can check the PR and see if my changes work for you

2021-06-08 17:09 UTC, tahesse commented
> I commited changes that (as far as I can tell) solve the issue and do pass the tests, so I am waiting on a response.
> 
> Perhaps you can check the PR and see if my changes work for you

Your changes work for me, that is why I ask for the status of this PR. It seems that there is one failing test due to less (?) code coverage.

2021-06-09 09:59 UTC, S-ecki commented
> Your changes work for me, that is why I ask for the status of this PR. It seems that there is one failing test due to less (?) code coverage.

I do not fully understand the code coverage problem, as my PR did not really change it (didnt add/remove tests and just added some null operators)

Perhaps @danvick can help us out

2021-07-05 08:32 UTC, merged